<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Keekee" failures="1" tests="1" name="SocialMediaTests" time="9.803" errors="0" timestamp="2025-06-29T16:12:38 IST">
  <testcase classname="testCases.TC005_AddToCart" name="verify_socialmedialinks" time="1.444">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception.
at testCases.TC005_AddToCart.verify_socialmedialinks(TC005_AddToCart.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verify_socialmedialinks -->
</testsuite> <!-- SocialMediaTests -->
